package dev.nexoclient.nexomod.tactical.locate;

import java.util.Arrays;
import java.util.Optional;

/**
 * The Minecraft versions a server's world can have been generated by — only the
 * ones where generation changed, so a server on 1.12.2 picks {@link #V1_11}
 * (same biomes and structures) rather than needing its own entry.
 *
 * <p>This matters because of ViaVersion and friends: the player's client is
 * 26.x, but the server's generator is whatever the server runs, and the same
 * seed yields a different world on each. {@link SeedWorldgen} can only build the
 * generator this jar ships, so only {@link #supported()} versions are searched;
 * the rest are selectable (so the index records the truth about the server) and
 * refused with a message rather than answered with coordinates that would be
 * wrong.
 *
 * <p>ponytail: the change list is from memory of the changelogs, not verified
 * against each version's jar — a missing entry means two versions share an entry
 * that should be split. 26.2 and 26.3 are assumed to generate like 26.1; correct
 * that here if a release changes worldgen.
 */
enum WorldgenVersion {
	V1_8("1.8", false),
	V1_9("1.9", false),
	V1_11("1.11", false),
	V1_13("1.13", false),
	V1_14("1.14", false),
	V1_15("1.15", false),
	V1_16("1.16", false),
	V1_16_2("1.16.2", false),
	V1_18("1.18", false),
	V1_18_2("1.18.2", false),
	V1_19("1.19", false),
	V1_19_3("1.19.3", false),
	V1_20("1.20", false),
	V1_21("1.21", false),
	V1_21_4("1.21.4", false),
	V26_1("26.1", true),
	V26_2("26.2", true),
	V26_3("26.3", true);

	static final WorldgenVersion LATEST = V26_3;

	private final String label;
	private final boolean supported;

	WorldgenVersion(String label, boolean supported) {
		this.label = label;
		this.supported = supported;
	}

	String label() {
		return label;
	}

	boolean supported() {
		return supported;
	}

	/** Entries saved before versions existed carry none, and were always the current generator. */
	static WorldgenVersion of(String label) {
		return find(label).orElse(LATEST);
	}

	/**
	 * The newest entry that is not newer than a game version like {@code 1.20.2}
	 * ("the generator that version used"), or empty if the text has no version in it.
	 */
	static Optional<WorldgenVersion> forGameVersion(String text) {
		java.util.regex.Matcher m = java.util.regex.Pattern.compile("(\\d+)\\.(\\d+)(?:\\.(\\d+))?").matcher(text == null ? "" : text);
		if (!m.find()) {
			return Optional.empty();
		}
		int[] wanted = parts(m.group());
		WorldgenVersion best = null;
		for (WorldgenVersion v : values()) {
			if (compare(parts(v.label), wanted) <= 0) {
				best = v;
			}
		}
		return Optional.ofNullable(best);
	}

	private static int[] parts(String version) {
		return Arrays.stream(version.split("\\.")).mapToInt(Integer::parseInt).toArray();
	}

	private static int compare(int[] a, int[] b) {
		for (int i = 0; i < Math.max(a.length, b.length); i++) {
			int x = i < a.length ? a[i] : 0;
			int y = i < b.length ? b[i] : 0;
			if (x != y) {
				return Integer.compare(x, y);
			}
		}
		return 0;
	}

	static Optional<WorldgenVersion> find(String label) {
		return Arrays.stream(values()).filter(v -> v.label.equals(label)).findFirst();
	}
}
